RedFW.Shared.Event:registerEvent("setWeather", function(weather)
    SetWeatherTypePersist(weather)
    SetWeatherTypeNow(weather)
    SetWeatherTypeNowPersist(weather)
    print("^8Weather set to " .. weather.."^0")
end)

CreateThread(function()
    RedFW.Client.Components.Callback:triggerServer('getWeather', function(weather)
        SetWeatherTypePersist(weather)
        SetWeatherTypeNow(weather)
        SetWeatherTypeNowPersist(weather)
        print("^8Weather set to " .. weather.."^0")
    end)
end)